# file: roles/postgresql/install/tasks/main.yml

- name: stop if running
  service: name=postgresql state=stopped
  ignore_errors: True

- name: remove Data directory if exists
  file: path=/var/lib/pgsql/data state=absent

- name: install postgresql
  yum: name={{ item }}
  with_items:
    - postgresql
    - postgresql-server
    - postgresql-libs
    - postgresql-contrib
    - python-psycopg2

- name: initdb
  shell: postgresql-setup initdb

- name: copy pg_hba.conf
  copy: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf group=postgres owner=postgres mode="u+rw,g-rwx,o-rwx"

- name: copy postgresql.conf
  copy: src=postgresql.conf dest=/var/lib/pgsql/data/postgresql.conf group=postgres owner=postgres mode="u+rw,g-rwx,o-rwx"

- name: start
  service: name=postgresql state=started  enabled=yes

- name: create database
  postgresql_db:
    name: "{{ dbname }}"
    encoding: "UTF-8"
    login_user: postgres
  become: True
  become_user: postgres

- name: create user
  postgresql_user:
    db: "{{ dbname }}"
    name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    priv: ALL
    state: present
    login_user: postgres
  become: True
  become_user: postgres
